import os
import time
clear = lambda: os.system('cls')
print('starting BAINS')
time.sleep(1)
clear()
print('loading.')
time.sleep(1)
clear()
print('loading..')
time.sleep(1)
clear()
print('loading...')
time.sleep(1)
clear()
print('loading.')
time.sleep(1)
clear()
print('loading..')
time.sleep(1)
clear()
print('loading...')
time.sleep(1)
clear()
time.sleep(1)
os.system("C:/Users/Екатерина/Desktop/bains/tkterm/tkterm.py")