import color
color.WIE_BLACK("              .-/+oossssoo+/-.               roma@DESKTOP-JNGIPM0                         ")
color.WIE_BLACK("          `:+ssssssssssssssssss+:`           --------------------                         ")
color.WIE_BLACK("        -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64  ")
color.WIE_BLACK("      .ossssssssssssssssssdMMMNysssso.       Kernel: 4.4.0-19041-Microsoft                ")
color.WIE_BLACK("     /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 4 hours, 7 mins                      ")
color.WIE_BLACK("    +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 672 (dpkg)                         ")
color.WIE_BLACK("   /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.16                           ")
color.WIE_BLACK("  .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Terminal: Windows Terminal                   ")
color.WIE_BLACK("  +sssshhhyNMMNyssssssssssssyNMMMysssssss+   CPU: AMD A4-5000 APU (4) @ 1.500GHz          ")
color.WIE_BLACK("  ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 3541MiB / 7627MiB                    ")
color.WIE_BLACK("  ossyNMMMNyMMhsssssssssssssshmmmhssssssso                                                ")
color.WIE_BLACK("  +sssshhhyNMMNyssssssssssssyNMMMysssssss+                                                ")
color.WIE_BLACK("  .ssssssssdMMMNhsssssssssshNMMMdssssssss.                                                ")
color.WIE_BLACK("   /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                                                 ")
color.WIE_BLACK("    +sssssssssdmydMMMMMMMMddddyssssssss+                                                  ")
color.WIE_BLACK("     /ssssssssssshdmNNNNmyNMMMMhssssss/                                                   ")
color.WIE_BLACK("      .ossssssssssssssssssdMMMNysssso.                                                    ")
color.WIE_BLACK("        -+sssssssssssssssssyyyssss+-                                                      ")
color.WIE_BLACK("          `:+ssssssssssssssssss+:`                                                        ")
color.WIE_BLACK("              .-/+oossssoo+/-.                                                            ")
